name: Update IPTV Playlist

on:
  schedule:
    # Запуск каждые 3 часа (формат UTC)
    - cron: '0 */3 * * *'
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    # Даем права на запись в репозиторий для сохранения плейлиста
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          # Установка самого браузера и системных библиотек для него
          playwright install chromium
          playwright install-deps chromium

      - name: Run grabber script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add playlist.m3u
          # Коммитим только если файл реально изменился
          git diff --quiet && git diff --staged --quiet || git commit -m "Update playlist $(date +'%Y-%m-%d %H:%M')"
          # Лекарство от ошибки 'rejected': подтягиваем изменения и ставим свои сверху
          git pull --rebase origin main
          git push origin main

